# =========================
# DATABASE - TESTS
# =========================
spring.datasource.url=jdbc:postgresql://10.129.227.133:5432/quick_transfer
spring.datasource.username=root
spring.datasource.password=postgresqlPW

spring.jpa.hibernate.ddl-auto=create-drop