spring.config.import=optional:file:.env[.properties]

# =========================
# APPLICATION NAME
# =========================
spring.application.name=quick-transfer
server.port=8080
server.servlet.context-path=/api

# =========================
# DATABASE - POSTGRESQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/quick_transfer
spring.datasource.username=backend
spring.datasource.password=postgresqlPW
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# SQL INIT
# =========================
spring.sql.init.mode=never

# =========================
# JSON
# =========================
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.serialization.indent-output=true

# =========================
# JWT
# =========================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

# =========================
# SECURITY
# =========================
spring.security.filter.dispatcher-types=async,request,error
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

# =========================
# CORS
# =========================
app.cors.allowed-origins=http://localhost:3000
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=Authorization,Content-Type,Accept
app.cors.allow-credentials=true

# =========================
# LOGS
# =========================
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always