# =========================
# DATABASE - TESTS
# =========================
spring.datasource.url=jdbc:postgresql://IP_DO_SERVIDOR:5432/seu_banco_de_dados
spring.datasource.username=root
spring.datasource.password=postgresqlPW

spring.jpa.hibernate.ddl-auto=create-drop